version: 2

dependencies:
  cache_directories:
    - node_modules

jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      # specify the version you desire here
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'yarn install'
  deploy:
    branches:
      ignore:
        - master
    docker:
      # specify the version you desire here
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'yarn install'
      - run:
          name: Retrieve production config
          command: 'curl $FIREBASE_PRODUCTION_CONFIG > ./src/environments/environment.prod.ts '
      - run:
         name: Build in production mode
         command: 'npm run build.prod'
      - run:
          name: Copy circle CI config
          command: 'mkdir ./dist/.circleci && cp ./.circleci/config.yml ./dist/.circleci/config.yml'
      - run:
          name: Deploy to master branch
          command: 'npm run deploy'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build