version: 2
branches:
  ignore:
    - master

dependencies:
  cache_directories:
    - node_modules

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'yarn install'
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'yarn install'
      - run:
          name: Retrieve production config
          command: 'curl $FIREBASE_PRODUCTION_CONFIG > ./src/environments/environment.prod.ts '
      - run:
          name: Deploy
          command: 'npm run deploy'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build