version: 2
branches:
  ignore:
    - master
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install globlal packages
          command: 'sudo npm install -g @angular/cli'
      - run:
          name: Install dependencies
          command: 'npm install'
      - run:
          name: Build project
          command: 'npm run build'
