version: 2
branches:
  ignore:
    - master
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install globlal packages
          command: 'sudo npm i -g @angular/cli angular-cli-ghpages'
      - run:
          name: Build project
          command: 'npm run build'
